package repro

import (
	"context"
	"reflect"
	"runtime"
	"testing"

	"github.com/bytedance/mockey"
)

// Mirrors code.byted.org/kv/redis-v6.Client
type RedisClient struct{ n string }

func (c *RedisClient) WithContext(ctx context.Context) *RedisClient {
	cc := *c
	return &cc
}

// Mirrors code.byted.org/kv/goredis.Client: embeds *RedisClient AND declares
// its own WithContext which internally calls the embedded one.
type GoredisClient struct {
	*RedisClient
	ctx context.Context
}

func (c *GoredisClient) WithContext(ctx context.Context) *GoredisClient {
	cc := *c
	cc.ctx = ctx
	cc.RedisClient = cc.RedisClient.WithContext(ctx)
	return &cc
}

func autogen(m reflect.Method) bool {
	f := runtime.FuncForPC(m.Func.Pointer())
	if f == nil {
		return false
	}
	file, _ := f.FileLine(m.Func.Pointer())
	return file == "<autogenerated>"
}

func TestResolve(t *testing.T) {
	c := &GoredisClient{RedisClient: &RedisClient{n: "x"}}
	tt := reflect.TypeOf(*c)
	for _, recv := range []reflect.Type{tt, reflect.PtrTo(tt)} {
		if m, ok := recv.MethodByName("WithContext"); ok {
			t.Logf("RESOLVE %v WithContext autogen=%v type=%v", recv, autogen(m), m.Type)
		}
	}
	got := reflect.TypeOf(mockey.GetMethod(c, "WithContext"))
	t.Logf("RESOLVE GetMethod -> %v", got)
}

func TestE2E(t *testing.T) {
	c := &GoredisClient{RedisClient: &RedisClient{n: "x"}}
	m := mockey.Mock(mockey.GetMethod(c, "WithContext")).Return(c).Build()
	defer m.UnPatch()
	_ = c.WithContext(context.Background())
	t.Log("E2E called ok")
}
