package repro

import (
	"context"
	"reflect"
	"runtime"
	"testing"

	"github.com/bytedance/mockey"
)

type NilInner struct{ n string }

func (c *NilInner) WithContext(ctx context.Context) *NilInner { return c }

// NilOuter embeds a *NilInner that is nil at GetMethod time -> deferred path,
// which is the branch 3b9352a added and which consults isAutogeneratedMethod.
type NilOuter struct {
	*NilInner
}

func (c *NilOuter) WithContext(ctx context.Context) *NilOuter { return c }

func ag(m reflect.Method) (string, bool) {
	f := runtime.FuncForPC(m.Func.Pointer())
	if f == nil {
		return "<nil funcforpc>", false
	}
	file, _ := f.FileLine(m.Func.Pointer())
	return file, file == "<autogenerated>"
}

func TestNilDeferredAutogen(t *testing.T) {
	var outer = &NilOuter{} // embedded *NilInner is nil
	tt := reflect.TypeOf(*outer)
	for _, recv := range []reflect.Type{tt, reflect.PtrTo(tt)} {
		if m, ok := recv.MethodByName("WithContext"); ok {
			file, is := ag(m)
			t.Logf("NILAG %v file=%q autogen=%v out=%v", recv, file, is, m.Type.Out(0))
		}
	}
	got := reflect.TypeOf(mockey.GetMethod(outer, "WithContext"))
	t.Logf("NILAG GetMethod -> %v", got)
}
